(function(){
  const root=document.querySelector("#dashboard"),config=window.MUCCI_CONFIG||{},core=window.MucciCards;
  if(!config.supabaseUrl||!config.supabaseAnonKey||!window.supabase){root.innerHTML='<div class="dashboard-notice"><strong>Setup required.</strong> Add the public Supabase URL and anon key to <code>config.js</code>, then run the supplied migration. No owner data is available until setup is complete.</div>';return;}
  const client=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey),fields=["name","company","title","phone","email","website","linkedin","instagram","address","bio","logo_url","profile_image_url"];
  const esc=(v)=>String(v||"").replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
  async function init(){const {data:{session}}=await client.auth.getSession();if(!session)return login();load(session.user);}
  function login(){root.innerHTML='<form id="login-form" class="saved-card"><h2>Owner sign in</h2><p>Enter the email connected to your card profile. We will send a secure sign-in link.</p><label>Email<input class="button button-secondary" required type="email" name="email" autocomplete="email"></label><button class="button button-primary">Send sign-in link</button><p id="login-message" role="status"></p></form>';document.querySelector("#login-form").addEventListener("submit",async(e)=>{e.preventDefault();const email=new FormData(e.currentTarget).get("email"),{error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:location.href}});document.querySelector("#login-message").textContent=error?error.message:"Check your email for the sign-in link.";});}
  async function load(){const {data:profiles,error}=await client.from("profiles").select("*").order("created_at");if(error){root.textContent=error.message;return;}const {data:cards}=await client.from("physical_cards").select("id,profile_id,public_token,card_label,is_active");render(profiles||[],cards||[]);}
  function render(profiles,cards){root.innerHTML=`<div class="saved-grid">${profiles.map((p)=>`<form class="saved-card profile-form" data-id="${p.id}"><h2>${esc(p.name)}</h2>${fields.map((f)=>`<label>${f.replaceAll("_"," ")} ${f==="bio"?`<textarea name="${f}">${esc(p[f])}</textarea>`:`<input name="${f}" value="${esc(p[f])}">`}</label>`).join("")}<label><input type="checkbox" name="is_active" ${p.is_active?"checked":""}> Profile active</label><button class="button button-primary">Save profile</button><p role="status"></p></form>`).join("")}</div><section><h2>Physical cards</h2><div class="saved-grid">${cards.map((c)=>{const url=core.cardUrl(config.publicSiteUrl,c.public_token);return `<article class="saved-card"><h3>${esc(c.card_label||"Physical card")}</h3><p><strong>NFC URL</strong><br><code>${esc(url)}</code></p><canvas data-qr="${esc(url)}"></canvas><div class="saved-card-actions"><button class="button button-secondary" data-copy="${esc(url)}">Copy URL</button><a class="button button-primary" href="${esc(url)}" target="_blank">Test profile</a></div><button class="button button-secondary" data-download>Download QR</button><p>${c.is_active?"Active":"Disabled"}</p></article>`}).join("")}</div></section><button class="button button-secondary" id="sign-out">Sign out</button>`;
    document.querySelectorAll(".profile-form").forEach((form)=>form.addEventListener("submit",save));document.querySelectorAll("[data-copy]").forEach((b)=>b.addEventListener("click",()=>navigator.clipboard.writeText(b.dataset.copy)));document.querySelectorAll("[data-qr]").forEach((canvas)=>{const qr=window.qrcode(0,"M");qr.addData(canvas.dataset.qr);qr.make();canvas.dataset.qrImage=qr.createDataURL(6,2);const image=new Image();image.onload=()=>canvas.getContext("2d").drawImage(image,0,0,canvas.width=210,canvas.height=210);image.src=canvas.dataset.qrImage;});document.querySelectorAll("[data-download]").forEach((button)=>button.addEventListener("click",()=>{const canvas=button.parentElement.querySelector("canvas"),a=document.createElement("a");a.download="mucci-card-qr.png";a.href=canvas.toDataURL("image/png");a.click();}));document.querySelector("#sign-out").addEventListener("click",async()=>{await client.auth.signOut();login();});}
  async function save(e){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form));fields.forEach((f)=>data[f]=data[f]||null);data.is_active=form.elements.is_active.checked;const {error}=await client.from("profiles").update(data).eq("id",form.dataset.id);form.querySelector('[role="status"]').textContent=error?error.message:"Saved.";}
  init();
})();
